# Output values from Flask Application module
# These outputs provide information about the created Flask container

# Name of the Flask container that was created  
output "container_name" {
  value = docker_container.flask_app.name # Returns "flask-app"
  # This is the container name that appears in Docker commands
}

# Unique ID of the Flask container (generated by Docker)
output "container_id" {
  value = docker_container.flask_app.id   # Returns container's unique identifier
  # Useful for debugging or monitoring the container
}

# Port number where Flask application is listening
output "flask_port" {
  value = "5000"                          # Flask default port
  # Users access the web application on this port
}
