# Output values from MySQL module - information about the created database
# These outputs can be used by other modules or displayed to users

# Name of the MySQL container that was created
output "container_name" {
  value = docker_container.mysql.name   # Returns "mysql-db"
  # Other containers use this name to connect to the database
}

# Unique ID of the MySQL container (generated by Docker)
output "container_id" {
  value = docker_container.mysql.id     # Returns container's unique identifier
  # Useful for debugging or advanced container management
}

# Port number where MySQL is listening for connections
output "mysql_port" {
  value = "3306"                        # Standard MySQL port
  # Applications use this port to connect to the database
}

# Name of the database created inside MySQL
output "database_name" {
  value = var.db_name                   # Returns the database name (e.g., "mylistdb")
  # This is the database our Flask app will use
}

# Username that applications should use to connect
output "database_user" {
  value = var.db_user                   # Returns the app username (e.g., "admin")
  # This user has permissions to access the application database
}
